### ISSUE TITLE
remain issue in typora_plugin 

### ISSUE THREAD

**Issue by obgnail** [obgnail/typora_image_uploader#1]
- https://github.com/obgnail/typora_plugin/issues/167
- https://github.com/obgnail/typora_plugin/issues/263

**Comment by Sun285714** [comment]
老哥你这个上传后无法访问啊

**Comment by obgnail** [comment]
@Sun285714 

你的图床仓库是这个吗？https://github.com/Sun285714/my_pictures/tree/main/image

我看到已经成功上传 5 个文件了。

已经可以成功引用了，我在本地测试成功了。如下图：

![IMG_2024-09-05_12-02-11](https://github.com/user-attachments/assets/69aacb00-d176-4b2b-b635-ac3ae84d00c6)

---

麻烦具体描述是如何无法访问的？

**Comment by Sun285714** [comment]
我，用Edge浏览器无法访问，但是用chrome能够访问。
但是在我的typora中也无法访问
![Uploading Snipaste_2024-09-05_14-58-04.png…]()

**Comment by Sun285714** [comment]
![Snipaste_2024-09-05_14-58-04](https://github.com/user-attachments/assets/f041c6bd-1934-4e2c-9336-f4c3fd571910)

**Comment by obgnail** [comment]
@Sun285714 

我这边是没有问题的。

![IMG_2024-09-05_16-02-47 (1)](https://github.com/user-attachments/assets/07f30924-4a30-40b6-96df-5137b990e281)

---

原因应该是你所在地区的网络难以直连 github。

你是在 chrome 里使用了代理吗？

如果你有代理，
1. 如果使用了 Rule/PAC 模式，有可能是没有为域名 raw.githubusercontent.com 添加准入列表
2. 也有可能你使用的代理软件没有将 Typora 添加准入列表
3. 你可以试试置为全局模式，看能不能解决问题。

> 网络问题，我这边爱莫能助。

**Comment by Sun285714** [comment]
@obgnail 
确实是的我在chrome中关闭代理也不能访问了
